Styles initial UI for chat feature
googleinterns/step123-2020 pull request #16
Opened 2020-07-16 22:07 UTC by vlop11

This branch works on styling the UI of the chat feature. This may change over time, but this a basic idea of how it should look.

2020-07-17 21:24 UTC, ahlschlager commented on src/main/java/templates/chat.soy
> +                    <li class="mdc-list-item" tabindex="0">
indent inside the for loop

2020-07-20 16:16 UTC, dylancastillo commented on src/main/webapp/chat.css
> +    margin: 0px;
nit: remove px after 0 throughout the file

2020-07-20 16:16 UTC, dylancastillo commented on src/main/webapp/chat.css
> +    margin: auto;
nit: alphabetize

2020-07-22 19:52 UTC, courtneywong requested changes

2020-07-22 19:52 UTC, courtneywong commented on src/main/webapp/updateChat.js
> +            });
I think the correct formatting here is 
```
const messageTemplate =
          templates.message.messageBubble({'message': json[i]});
```

2020-07-22 21:03 UTC, courtneywong approved these changes

2020-07-22 21:04 UTC, sporkert approved these changes

2020-07-22 22:17 UTC, merged