Connect the map to Calendar, with date picker
googleinterns/step123-2020 pull request #22
Opened 2020-07-30 00:06 UTC by ahlschlager

2020-07-30 16:03 UTC, vlop11 commented on src/main/java/com/google/sps/servlets/SortedMarkersServlet.java
> +        SortedMarkers sorted = new SortedMarkers(mapEvents);
I would name this something a little more descriptive. maybe sortedEvents or sortedMarkers?

2020-07-30 16:06 UTC, vlop11 commented on src/main/java/com/google/sps/utils/StringConstants.java
> +  public static final String REFERER_HEADER = "Referer";
look at Dylan's file for ordering, he put all the template names at the top and keys and referer should be in alphabetical order in the chat constants section

2020-07-30 19:21 UTC, sporkert requested changes
Can you check the formatting? Maybe something happened when you were moving files over.

There's a lot of lines that show just a space added.

2020-07-30 19:21 UTC, sporkert commented on src/main/java/com/google/sps/servlets/SortedMarkersServlet.java
> +        // The events are from the calendar though
You can take out this line

2020-07-30 19:21 UTC, sporkert commented on src/main/java/com/google/sps/servlets/SortedMarkersServlet.java
> +        // CalendarID and group Name are both hardcoded for now
Can you rephrase this to something like TODO: Replace hard-coded calendarID and group name when ____

That way it's more clear to the reader what you're waiting for

2020-07-30 19:21 UTC, sporkert commented on src/main/java/com/google/sps/servlets/MapServlet.java
> +            ImmutableMap.of(GROUPS_KEY, ImmutableList.of(groupMap, groupMap2), "key", apiKey));
replace "key" with a constant

2020-07-31 01:13 UTC, sporkert requested changes

2020-07-31 01:13 UTC, sporkert commented on src/main/java/com/google/sps/EventMarker.java
> +    private static final DateTimeFormatter FORMAT = DateTimeFormatter.ofPattern("EEEE, MMMM dd, yyyy hh:mm a");
private static final variables should go at the top

2020-07-31 01:13 UTC, sporkert commented on src/main/java/com/google/sps/EventMarker.java
>      private String description;
I know this isn't part of your change, but while you're here could you alphabetize these?

2020-07-31 01:13 UTC, sporkert commented on src/main/java/com/google/sps/EventMarker.java
> +    private void simpleDate() {
rename this to formatSimpleDate()?

2020-07-31 01:13 UTC, sporkert commented on src/main/java/com/google/sps/servlets/MapServlet.java
> +            Entity user = new Entity(USER_KIND, userEmail);
Is there a way to detect if a user does not exist without waiting for an exception to be thrown?

Exceptions should really be used for actual exceptions that you can't really predict. If you can predict it (which it looks like you can here), use an if/else and handle the edge case.

2020-08-03 17:25 UTC, sporkert requested changes

2020-08-03 17:25 UTC, sporkert commented on src/main/java/com/google/sps/EventMarker.java
>      private String description;
Thanks!

2020-08-03 17:25 UTC, sporkert commented on src/main/java/com/google/sps/EventMarker.java
> +        dateOutput = OffsetDateTime.parse(date.toStringRfc3339()).format(FORMAT);
Are there tests already for date formatting? If not, please add :)

2020-08-03 17:25 UTC, sporkert commented on src/main/java/com/google/sps/servlets/SortedMarkersServlet.java
> +
nit: remove extra newline

2020-08-03 17:25 UTC, sporkert commented on src/main/java/com/google/sps/utils/ServletUtils.java
> +
remove newline

2020-08-03 17:25 UTC, sporkert commented on src/main/java/com/google/sps/utils/ServletUtils.java
> +    return groupsList;
you can condense this into one line and just do `return groupsListBuilder.build();`

2020-08-03 21:26 UTC, sporkert approved these changes

2020-08-03 21:26 UTC, sporkert commented on src/main/webapp/mapScript.js
> +    document.getElementById("date").value = "";
use constant variable for `date`

2020-08-03 21:26 UTC, sporkert commented on src/main/java/com/google/sps/utils/ServletUtils.java
> +        System.out.println("SYDNEY --- THE GROUP IS INVALID");
remove your name? :)

2020-08-03 21:48 UTC, ahlschlager commented on src/main/webapp/mapScript.js
> +    document.getElementById("date").value = "";
Resolved offline

2020-08-03 21:57 UTC, sporkert approved these changes

2020-08-03 22:23 UTC, vlop11 commented on src/main/java/com/google/sps/servlets/MapServlet.java
>          // Reads API Key and HTTP referer from file
you might want to change your comment here, since you're no longer reading the referer

2020-08-03 22:28 UTC, vlop11 approved these changes
Left a couple comments, but nothing major

2020-08-03 22:36 UTC, merged