Adds functionality for joining a group
googleinterns/step123-2020 pull request #25
Opened 2020-07-31 22:20 UTC by vlop11

Since the actual method for a user joining a group is already written, I will mostly be focusing on the front-end:

- Make the JOIN button for each group call the PUT method that's already written
- Once the button is pressed, render a new button that says JOINED and is not clickable
- Possibly have every already joined group have the above JOINED button

2020-08-03 17:29 UTC, sporkert requested changes

2020-08-03 17:29 UTC, sporkert commented on src/main/java/com/google/sps/servlets/GroupsServlet.java
> +        ImmutableList<Long> userGroups= ImmutableList.copyOf(SoyRendererUtils.getGroupIdList(request));
nit: add a space before the `=`

2020-08-03 18:55 UTC, courtneywong requested changes

2020-08-03 18:55 UTC, courtneywong commented on src/main/java/com/google/sps/servlets/GroupsServlet.java
> +            user.setProperty(GROUPS_KEY, groups);
ImmutableList.Builder?

2020-08-03 18:55 UTC, courtneywong commented on src/main/java/com/google/sps/utils/SoyRendererUtils.java
> +        List<Long> userGroups = new ArrayList<Long>();
ImmutableList.Builder?

2020-08-03 18:55 UTC, courtneywong commented on src/main/java/com/google/sps/utils/SoyRendererUtils.java
> +            // Hardcoded group added to user's list //
You don't need the // at the end.

2020-08-03 18:55 UTC, courtneywong commented on src/main/java/com/google/sps/utils/SoyRendererUtils.java
> +
remove this newline

2020-08-03 18:55 UTC, courtneywong commented on src/main/webapp/groups.js
> +        body: groupId
Add a trailing comma here.

2020-08-03 18:55 UTC, courtneywong commented on src/main/webapp/groups.js
> +    goog.dom.setProperties(joinButton, {"disabled": "true"});
Can you use setAttribute here? `joinButton.setAttribute('setAttribute', true)`

2020-08-03 18:55 UTC, courtneywong commented on src/main/webapp/groups.js
> +
Sorry I didn't see this before, but there shouldn't be any double quotation marks in JS. Prefer to use single quotes. Can you fix it throughout teh file? ie "/groups" should be '/groups'.

2020-08-03 21:18 UTC, ahlschlager approved these changes

2020-08-04 04:34 UTC, dylancastillo approved these changes

2020-08-04 04:34 UTC, dylancastillo commented on src/main/webapp/groups.js
> +    fetch('/calendar?groupId=' + groupId, {
shouldn't this be newGroupId?

2020-08-05 00:02 UTC, courtneywong approved these changes

2020-08-05 17:25 UTC, sporkert approved these changes

2020-08-05 17:57 UTC, merged